// GENERATED by tatara-rust-derive::PerFieldDeriveSpec.
use proc_macro::TokenStream;
use quote::quote;
use syn::{Data, DataStruct, DeriveInput, Fields, parse_macro_input};

#[proc_macro_derive(TakeAll)]
pub fn derive_take_all(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    let self_name = &input.ident;

    let fields = match &input.data {
        Data::Struct(DataStruct { fields: Fields::Named(named), .. }) => &named.named,
        _ => {
            return syn::Error::new_spanned(self_name, "PerFieldDerive requires a named-fields struct").to_compile_error().into();
        }
    };

    let per_field = fields.iter().map(|f| {
        let field_name = f.ident.as_ref().expect("named field has ident");
        let field_ty = &f.ty;
        let method_ident = quote::format_ident!("take_{}", field_name.to_string());
        quote! {
            pub fn #method_ident(&mut self) -> #field_ty where #field_ty: ::std::default::Default { ::std::mem::take(&mut self.#field_name) }
        }
    });

    let expanded = quote! {
        impl #self_name {
            #(#per_field)*
        }
    };
    TokenStream::from(expanded)
}
